### ISSUE TITLE
Question about JAAD annotations

### ISSUE THREAD

**Issue by d-zh** [HaziqRazali/Pedestrian-Intention-Prediction#2]
Hi,
   I want to know how to get the annotations of JAAD. These annotations named “singletxt_train_3s”,  “singletxt_val_3s”,  “singletxt_pre_train_3s” are not officially provided by JAAD. And I did not find scripts or codes to generate them.
  Thanks!

**Comment by D4edalus** [comment]
i'm also curious how to generate those files. please provide code to generate them.

**Comment by dlengerer** [comment]
Hi, 
did someone find a solution for the issue?
@HaziqRazali could you help us please?

**Comment by SebLefeb** [comment]
I've been able to generate the files required through this [script](https://github.com/vita-epfl/bounding-box-prediction/blob/master/2D/prepare_data.py). You have to change a lot of things to be able to get all the required data out of the .XML annotations to the .CSV file the system expects
Here's the file that I modified : [prepare_data.zip](https://github.com/HaziqRazali/Pedestrian-Intention-Prediction/files/9048307/prepare_data.zip)

**Comment by deprecatedfrhylw** [comment]
> 

hello, what are the train/val/test ratios when you ran the script? or are those values not that important?

**Comment by SebLefeb** [comment]
Values should be between 0 and 1, totalling 1. So, I used something around 0.7 for train, 0.1 for pre-train and 0.2 for val.

**Comment by deprecatedfrhylw** [comment]
thx a lot 😘😘

**Comment by SujayNiranjan** [comment]
@d-zh, were you able to replicate the results?
